is_ackermann: true
linear_scale: 1
max_positive_linear_velocity: 1
max_negative_linear_velocity: -1
angular_scale: 1
max_positive_angular_position: 0.6 # in radians
max_negative_angular_position: -0.6 # in radians
